config/routes.rb
Rails.application.routes.draw do
  root 'analytics#index'

  resources :determinations
  resources :analytics

end

app/models/analytic.rb
class Analytic < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/center.rb
class Center < ApplicationRecord
end

app/models/chapter.rb
class Chapter < ApplicationRecord
end

app/models/determination.rb
class Determination < ApplicationRecord
end

app/models/doctor.rb
class Doctor < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  before_action :set_analytic, only: [:show, :edit, :update, :destroy]

  # GET /analytics
  # GET /analytics.json
  def index
    @analytics = Analytic.all
  end

  # GET /analytics/1
  # GET /analytics/1.json
  def show
  end

  # GET /analytics/new
  def new
    @analytic = Analytic.new
  end

  # GET /analytics/1/edit
  def edit
  end

  # POST /analytics
  # POST /analytics.json
  def create
    @analytic = Analytic.new(analytic_params)

    respond_to do |format|
      if @analytic.save
        format.html { redirect_to @analytic, notice: 'Analytic was successfully created.' }
        format.json { render :show, status: :created, location: @analytic }
      else
        format.html { render :new }
        format.json { render json: @analytic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /analytics/1
  # PATCH/PUT /analytics/1.json
  def update
    respond_to do |format|
      if @analytic.update(analytic_params)
        format.html { redirect_to @analytic, notice: 'Analytic was successfully updated.' }
        format.json { render :show, status: :ok, location: @analytic }
      else
        format.html { render :edit }
        format.json { render json: @analytic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /analytics/1
  # DELETE /analytics/1.json
  def destroy
    @analytic.destroy
    respond_to do |format|
      format.html { redirect_to analytics_url, notice: 'Analytic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_analytic
      @analytic = Analytic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def analytic_params
      params.fetch(:analytic, {})
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/determinations_controller.rb
class DeterminationsController < ApplicationController
  before_action :set_determination, only: [:show, :edit, :update, :destroy]

  # GET /determinations
  # GET /determinations.json
  def index
    @determinations = Determination.all
  end

  # GET /determinations/1
  # GET /determinations/1.json
  def show
  end

  # GET /determinations/new
  def new
    @determination = Determination.new
  end

  # GET /determinations/1/edit
  def edit
  end

  # POST /determinations
  # POST /determinations.json
  def create
    @determination = Determination.new(determination_params)

    respond_to do |format|
      if @determination.save
        format.html { redirect_to @determination, notice: 'Determination was successfully created.' }
        format.json { render :show, status: :created, location: @determination }
      else
        format.html { render :new }
        format.json { render json: @determination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /determinations/1
  # PATCH/PUT /determinations/1.json
  def update
    respond_to do |format|
      if @determination.update(determination_params)
        format.html { redirect_to @determination, notice: 'Determination was successfully updated.' }
        format.json { render :show, status: :ok, location: @determination }
      else
        format.html { render :edit }
        format.json { render json: @determination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /determinations/1
  # DELETE /determinations/1.json
  def destroy
    @determination.destroy
    respond_to do |format|
      format.html { redirect_to determinations_url, notice: 'Determination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_determination
      @determination = Determination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def determination_params
      params.fetch(:determination, {})
    end
end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/determinations_helper.rb
module DeterminationsHelper
end

app/views/analytics/_form.html.erb
<%= form_for(analytic) do |f| %>
  <% if analytic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(analytic.errors.count, "error") %> impiden que se grabe esta analítica:</h2>

      <ul>
      <% analytic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
    <div class="small-6 columns">
      <%= f.label :patient_id, "Paciente"%>
      <%= f.text_field :patient_id %>
     </div>
    <div class="row">
      <div  class="small-1 columns">
        <%= f.label :extracted_at, "Fecha Extracción"%>
        <%= f.text_field :extracted_at %>
      </div>
      <div class="small-6 columns">
        <%= f.label :extracted_in, "Centro de Extracción"%>
        <%= f.text_field :extracted_in %>
      </div>
    </div>
    <div class="row">
      <div class="small-1 columns">
        <%= f.label :prescribed_at, "Fecha de prescripción"%>
        <%= f.text_field :prescribed_at %>
      </div>
      <div  class="small-1 columns">
        <%= f.label :doctor_id, "Médico"%>
        <%= f.text_field :doctor_id %>
      </div>
      <div  class="small-6 columns">
        <%= f.label :prescribed_by, "Prescito por "%>
        <%= f.text_field :prescribed_by %>
      </div>
    </div>
    <div class="row">
      <div class="small-4 columns">
        <%= f.label :reason, "Razón" %>
        <%= f.text_field :reason %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/analytics/edit.html.erb
<h1>Editing Analytic</h1>

<%= render 'form', analytic: @analytic %>

<%= link_to 'Show', @analytic %> |
<%= link_to 'Back', analytics_path %>

app/views/analytics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Analytics</h1>

<table>
  <thead>
    <tr>
      <th>Paciente</th>
      <th>Fch.Extracción</th>
      <th>Lugar</th>
      <th>Fch.Prescripción</th>
      <th>Prescrito por</th>
      <th>Motivo</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @analytics.each do |analytic| %>
      <tr>
        <td><%= @nalytic.id %></td>
        <td><%= @analityc.extracted_at %></td>
        <td><%= @analityc.extracted_by %></td>
        <td><%= @analityc.reason %></td>
        <td><%= @analityc.id %></td>
        <td><%= link_to 'Show', analytic %></td>
        <td><%= link_to 'Edit', edit_analytic_path(analytic) %></td>
        <td><%= link_to 'Destroy', analytic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Analytic', new_analytic_path %>

app/views/analytics/new.html.erb
<h1>Nueva Analítica</h1>

<%= render 'form', analytic: @analytic %>

<%= link_to '<< Volver', analytics_path %>

app/views/analytics/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_analytic_path(@analytic) %> |
<%= link_to 'Back', analytics_path %>

app/views/determinations/_form.html.erb
<%= form_for(determination) do |f| %>
  <% if determination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(determination.errors.count, "error") %> prohibited this determination from being saved:</h2>

      <ul>
      <% determination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/determinations/edit.html.erb
<h1>Editing Determination</h1>

<%= render 'form', determination: @determination %>

<%= link_to 'Show', @determination %> |
<%= link_to 'Back', determinations_path %>

app/views/determinations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Determinations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @determinations.each do |determination| %>
      <tr>
        <td><%= link_to 'Show', determination %></td>
        <td><%= link_to 'Edit', edit_determination_path(determination) %></td>
        <td><%= link_to 'Destroy', determination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Determination', new_determination_path %>

app/views/determinations/new.html.erb
<h1>New Determination</h1>

<%= render 'form', determination: @determination %>

<%= link_to 'Back', determinations_path %>

app/views/determinations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_determination_path(@determination) %> |
<%= link_to 'Back', determinations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>